apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-deployment
  labels:
    app: lab1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80