apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: quote-api
  labels:
    app: quote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
      - name: quote-api
        image: gcr.io/acn-devops-upskilling-gcp/quote-api-hamza:0.0.2 # {"$imagepolicy": "flux-system:quote-api"}
        imagePullPolicy: Always
        env:
          - name: QUOTE_API_USER
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: user
          - name: QUOTE_API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: basic-auth
                key: password

