---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: quote-api
  namespace: flux-system
spec:
  image: gcr.io/acn-devops-upskilling-gcp/quote-api-hamza
  interval: 1m0s

