---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: quote-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: quote-api
  policy:
    semver:
      range: 0.0.x

