apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: quote-api
spec:
  encryptedData:
    password: AgA4WwmlL39NOimPF04EuK4im9A5s9cOT9xafE/nRsoYHHJrl8owDPvTjWw4yxMIpo9Q3ZxJ7RKGjjgTSFosPLft/UaSdBd8nlVUpCXlRm+KxgP7km04MPrLPqA+uf45OW/6KaYA6d7tEhgZcIkF9DtSOTvE2Va+H8AwZQ2j6Vuuovl419oOoFX6JKPnyNo7RaXvOy0aYz6OApQPGbhUm0rqKdTE2RcOgzPbafEvZ+0mNxvIb5JML6Ngazd58939HXTe88JG9dyY3vVCR5Sec6PkEBHHaE9RzQSJzndrj084UZGH71k1Md3lqeBusjZGs/9lYuVi8Ae8ina1CzajFktDtY6W+XF0qlnXnYTgGpywjRdAotSGdbHkuNAidMeN3UP9+DBctwo1WSLzZISR/GCIWSm7oOmDWguHWjH/F9VKi2GnsQKuRhVZgtvOw8JTGS5b4ycJVmj6vJSbrdfruBXwbXIRGNNXpM7CoHV+H40MocdwvB7xx961jJZVVY/TZ11WJVv+KaoCMTV+zZaGrxHE6Ues2dIMgURzu8KqOT3C4t7LkXgQRApBhj2yICnUYrH20ZlOJYceU6vXzNJAjsqJih9RrpcSNV4+nlhkjuiKGYOi5qyAmfuK2u8GoWU2VdwrSmJh/DCJAoUlGzloMMrJeBfy+llvRxItOfKHXNZkWVNt913W4l//HJC002grdFJuWvoirQ==
    user: AgBa+8TtyHaNKt+jJaoYXYhl4T+3T2xpIiBq/HVsTD6Jio3jekXtzAu4AlDpm9xPLsou+kaZft3R4Vj1nPlfVXfn9e2QWLzZo54vNes8rMC0b3MGIwFO5nJgOw6Exv44tBAb93KgDjOQVmNPa0erLgduq66M6yQGNf0HSY8h0nYrYcQL+WfW2qj4/PoqC+K+OLrsG//ZDmiFJ9Mq4iPcaZlyKRiYAmgoPDLwhM4UDWAvFGibowMQKatNdHXFQ17Sj8paldBKSxgQfCaMEv89LvP3B1jJJzrpIS5uzBu+qnzvs/gDR/nGS1wxkuivXWXXmEeLEIqDO+6+ztvIGQ4r1mrIqTjnvjqazyO8YFPWk4vgKZ3QzPdAdB3pMysscgTDDBQfQOzdc/NQ/tybpbGllNKeDqK66Adc/rwVB3ctQY1EJJihvJAB5n6GGbMllCLKbIybO6HkblIFZAT871WNezZWsMgHkHP0QEFF+0B1StR3w5yVVQMoGTf9atohCLdO9u0zcbBUErlwILvgm5CDpxKD91gSeQxLbsqdYKHSkIm4r7wRU92NUeWIfJgtwloD9YawEVFHTo8BzHnwiPKtKWGdjKy35sfA4rJ5Y+sGK+cSDHTPjvOYIC69LkTF1cgQ6RfCt2XTXJUvI1icoAjQbO/Gp9zLZCr1PHGjjh+AweNe+ynDIwI2Ct9gHX7fm9XqKsZbLuF2/og6dIwF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: quote-api

